# Translations template for networking-powervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the networking-powervm
# project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: networking-powervm 1.0.0.0rc2.dev34\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-04-14 09:09-0400\n"
"PO-Revision-Date: 2016-04-14 09:09-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.2\n"

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:177
#, python-format
msgid "Unable to parse URI %s for provision request assessment."
msgstr "Não é possível analisar o URI %s para avaliação de solicitação de provisão."

#: networking_powervm/plugins/ibm/agent/powervm/agent_base.py:495
msgid "Error has been encountered and logged.  The agent will retry again."
msgstr "Erro foi encontrado e registrado. O agente tentará novamente."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:158
msgid "An error occurred while attempting to update the PVID of the virtual NIC."
msgstr "Ocorreu um erro ao tentar atualizar o PVID do NIC virtual."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:369
#, python-format
msgid "Cleaning up VLAN %(vlan)s from the system. It is no longer in use."
msgstr "Limpando o VLAN%(vlan)s do sistema. Ele não está mais em uso."

#: networking_powervm/plugins/ibm/agent/powervm/sea_agent.py:427
#, python-format
msgid ""
"Unable to determine the Network Bridge (Shared Ethernet Adapter) for "
"physical network %s.  Will be unable to determine appropriate "
"provisioning action."
msgstr ""
"Não é possível determinar a ponte de rede (adaptador Ethernet compartilhado) para "
"a rede física %s.  Não será possível determinar a ação "
"de fornecimento apropriada."

#: networking_powervm/plugins/ibm/agent/powervm/utils.py:142
msgid ""
"The bridge_mappings for the agent was not specified.  There was exactly "
"one Network Bridge on the system.  Agent is assuming the default network "
"is backed by the single Network Bridge."
msgstr ""
"O bridge_mappings para o agente não foi especificado. Há exatamente "
"uma ponte de rede no sistema. O agente está assumindo a rede padrão "
"é suportado pela única ponte de rede."

#: networking_powervm/plugins/ibm/agent/powervm/utils.py:325
msgid "No NetworkBridges detected on the host."
msgstr "Nenhum NetworkBridges detectado no host."


# ENGL1SH_VERS10N 36276_3 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 37
# T9N_SH1P_STR1NG PV131AAP001 3
